---
title: Family Cloud
favicon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/home-assistant.png
theme: dark
color: slate
headerStyle: clean
layout:
  Cloud:
    style: row
    columns: 3
  Media:
    style: row
    columns: 2
  Outils:
    style: row
    columns: 3
